[package]
name = "bosto/test-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
cmdr = "evaera/cmdr@1.12.0"
Networker = "leifstout/networker@0.2.1"

[server-dependencies]
Profileservice = "firebird702/profileservice@1.1.0"